Added "Clear all" button to LOI selection part of onboarding flow
google/ground-platform pull request #1098
Opened 2023-06-09 20:34 UTC by nwkotto

The "Clear all" button clears out existing LOIs on the survey one by one, in quick succession.

2023-06-09 20:39 UTC, nwkotto commented
https://screenshot.googleplex.com/BzdKzuisfAWvfnr

2023-06-11 04:39 UTC, DaoyuT requested changes
Looks good in general

2023-06-11 04:39 UTC, DaoyuT commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +  @Input() shouldEnableDrawingTools = true;
Did you mean to include this?

2023-06-11 04:39 UTC, DaoyuT commented on web/src/app/pages/main-page-container/main-page/main-page.component.ts
> +  shouldEnableDrawingTools = true;
Did you mean to include this?

2023-06-11 19:22 UTC, nwkotto commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +  @Input() shouldEnableDrawingTools = true;
Whoops, I did not. Removed.

2023-06-11 19:22 UTC, nwkotto commented on web/src/app/pages/main-page-container/main-page/main-page.component.ts
> +  shouldEnableDrawingTools = true;
Whoops, I did not. Removed.

2023-06-12 15:23 UTC, DaoyuT approved these changes
LGTM

2023-06-23 16:18 UTC, merged