Add logic to retrieve correct setup phase
google/ground-platform pull request #1114
Opened 2023-07-18 22:03 UTC by os-micmec

Now that we have the task definition component

2023-07-25 14:27 UTC, gino-m requested changes
LG, just maybe revert the two package-lock.json files which I think got updated accidentally.

2023-07-25 14:27 UTC, gino-m commented on web/src/app/pages/create-survey/create-survey.component.ts
> +  // TODO: when we refresh, the setupPhase below is always displayed for a split of a second.
Please add issue number in TODO(#..).

2023-08-01 15:24 UTC, gino-m commented on web/src/app/pages/create-survey/create-survey.component.ts
> +  // TODO: when we refresh, the setupPhase below is always displayed for a split of a second.
Gentle ping!

2023-08-01 17:01 UTC, os-micmec commented on web/src/app/pages/create-survey/create-survey.component.ts
> +  // TODO: when we refresh, the setupPhase below is always displayed for a split of a second.
Done!

2023-08-01 17:06 UTC, gino-m approved these changes
Thanks for the fix!

2023-08-01 17:06 UTC, os-micmec commented
Also removed the package-lock files

2023-08-01 17:11 UTC, merged