Added data collection component
google/ground-platform pull request #1127
Opened 2023-08-18 16:48 UTC by nwkotto

This component introduces radio button cards, meant to be included in the onboarding flow, for setting who decides where data can be collected.

2023-08-18 18:24 UTC, os-micmec submitted a review, later dismissed

2023-08-21 13:41 UTC, gino-m approved these changes

2023-08-21 13:41 UTC, gino-m commented on web/src/app/pages/create-survey/data-collection/data-collection.module.ts
> +export class DataCollectionModule {}
Nit: Data collection in the context of Ground refers to the actual entry of field data by data collections. Can we rename this to something self-descriptive that doesn't collide with that name? 

In plain-English: "This component allows survey organizers to select who can specify data collection sites (i.e., locations of interest for which data is to be collected)." So maybe something like "LoiPermissionsComponent"?

2023-08-21 13:42 UTC, gino-m requested changes
One nit, otherwise LG!

2023-08-29 17:18 UTC, DaoyuT approved these changes
LGTM

2023-08-29 17:19 UTC, DaoyuT commented
@gino-m please stamp again if you think that one nit has been addressed :^)

2023-08-29 19:04 UTC, gino-m approved these changes
LGTM, thanks @nwkotto !

2023-08-31 20:13 UTC, gino-m approved these changes

2023-08-31 21:03 UTC, merged