Add support for geometry tasks in submission details view
google/ground-platform pull request #1472
Opened 2024-02-02 16:05 UTC by amysorto

[Geometry tasks.webm](https://github.com/google/ground-platform/assets/8575252/6671b0ce-3d77-45fb-8443-d5cb787058f1)

2024-02-02 17:11 UTC, gino-m commented
Hi @amysorto! It looks like the geometry annotations (geometry task responses, non-LOI markers and polygons on the map) don't show their corresponding number shown in the panel. Want to file a TODO and a bug to do in a follow-up?

See designs here:

![image](https://github.com/google/ground-platform/assets/228050/aadc2674-b67c-43e0-9ce3-803e175f030f)

2024-02-02 17:20 UTC, gino-m requested changes

2024-02-02 17:20 UTC, gino-m commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +      this.submissionService.getSelectedSubmission$().subscribe(submission => {
Would this cause a race condition with the `submissionId` and `locationOfInterestId` above?

2024-02-02 17:20 UTC, gino-m commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +      this.navigationService.getSubmissionId$().subscribe(id => {
We already subscribe to changes to submissionId above, perhaps this should live there?

2024-02-02 17:20 UTC, gino-m commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +        this.showSubmissionGeometry = id ? true : false;
Is this equivalent to`!!id`?

2024-02-02 17:20 UTC, gino-m commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +        if (this.showSubmissionGeometry === true) {
Do we need `=== true` here?

2024-02-07 12:38 UTC, amysorto commented
> Hi @amysorto! It looks like the geometry annotations (geometry task responses, non-LOI markers and polygons on the map) don't show their corresponding number shown in the panel. Want to file a TODO and a bug to do in a follow-up?
> 
> See designs here:
> 
> ![image](https://private-user-images.githubusercontent.com/228050/301918809-aadc2674-b67c-43e0-9ce3-803e175f030f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMDk3ODgsIm5iZiI6MTcwNzMwOTQ4OCwicGF0aCI6Ii8yMjgwNTAvMzAxOTE4ODA5LWFhZGMyNjc0LWI2N2MtNDNlMC05Y2UzLTgwM2UxNzVmMDMwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxMjM4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDNmMDQ0NDhlN2FlNTRmMjU4ODZlYjg3N2RhNDM5ZTE4OGRjOWYxMWViZTQzZmZjZjhkMDcxYjk1ZDliOTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.es_ddR6ZRViT3tOx1f7SRaM9Ri87kKjvSrjszBavM30)

Tracking in #1477

2024-02-07 14:39 UTC, gino-m approved these changes

2024-02-07 16:15 UTC, merged