WHISP integration
google/ground-platform pull request #1490
Opened 2024-02-16 21:22 UTC by rfontanarosa

close #1420

2024-02-16 21:28 UTC, gino-m commented on functions/src/on-write-loi.ts
> +  if (loiId) {
![image](https://github.com/google/ground-platform/assets/228050/84901bf7-a64f-47fc-8916-6efdc5f76265)

2024-02-16 21:29 UTC, gino-m commented on functions/src/on-write-loi.ts
> +    if (loi) {
![image](https://github.com/google/ground-platform/assets/228050/84901bf7-a64f-47fc-8916-6efdc5f76265)

2024-02-16 21:32 UTC, gino-m requested changes
A few early comments. Thanks!

2024-02-16 21:32 UTC, gino-m commented on functions/src/on-write-loi.ts
> +      const job = survey.data()?.jobs[loi?.jobId];
`?` after `loi` shouldn't be needed here since you checked this already.

2024-02-16 21:32 UTC, gino-m commented on functions/src/on-write-loi.ts
> +        job.tasks
Can't job be null here?

2024-02-16 21:32 UTC, gino-m commented on functions/src/on-write-loi.ts
> +      ).find(([_, task]) => task.addLoiTask);
You can probably more the logic that searches for the task with `addLoi` into `datastore.ts`

2024-02-20 14:41 UTC, rfontanarosa commented on functions/src/on-write-loi.ts
> +  if (loiId) {
![SF2](https://github.com/google/ground-platform/assets/10047945/d72048fe-435d-4296-8704-9d9febccbb55)

2024-02-20 14:42 UTC, rfontanarosa commented on functions/src/on-write-loi.ts
> +    if (loi) {
![SF2](https://github.com/google/ground-platform/assets/10047945/9d7693ad-189a-4b86-8220-b5d0e86af4fd)

2024-03-04 16:47 UTC, gino-m commented on functions/src/common/broadcast-survey-update.ts
> +  // Messages are sent without a payload so that they can collapsed. Collapsible
Please add tsdoc for this method: 
"Sends an empty message to clients subscribed to the specified topic."

Also please move this block into the tsdoc.

2024-03-04 17:10 UTC, gino-m commented on functions/src/on-create-loi.ts
> +const getIntegrationProperties = async (
Let's use `function` declaration style here and below for consistency.

2024-03-04 17:11 UTC, gino-m commented on functions/src/on-create-loi.ts
> +): Promise<{[key: string]: string}> => {
Please add or use an existing a typedef for `Properties`. Also note that the values can be `string | number`.

2024-03-04 17:13 UTC, gino-m commented on functions/src/on-create-loi.ts
> +const getIntegrationProperties = async (
Naming nit: `fetchProperties` to make it clear this is going out over the wire.

2024-03-04 17:14 UTC, gino-m commented on functions/src/on-create-loi.ts
> +  await Promise.all(
Please decompose business logic called here.

2024-03-04 17:17 UTC, gino-m requested changes
Comments inline.

2024-03-04 19:21 UTC, gino-m commented on functions/src/on-create-loi.ts
> +      const {url, prefix} = propertyGenerator as PropertyGenerator;
You can merge these two lines into one

2024-03-04 19:21 UTC, gino-m commented on functions/src/on-create-loi.ts
> +      if (prefix) properties = removePrefixedKeys(properties, prefix);
Add here: `if (!url) return`

2024-03-04 19:21 UTC, gino-m commented on functions/src/on-create-loi.ts
> +      if (url) {
Then you can remove this nested condition

2024-03-04 19:22 UTC, gino-m commented on functions/src/on-create-loi.ts
> +        properties = {
`return { ...properties, ...(`

2024-03-04 19:24 UTC, gino-m commented on functions/src/on-create-loi.ts
> +  return json?.data[0] || {};
Please add comment explaining that we expect data to be returned as the first element of an array in a field under JSON root called `data`.

2024-03-04 19:25 UTC, gino-m commented on functions/src/on-create-loi.ts
> +function prefixKeys(obj: Properties, prefix: string) {
Please add tsdoc

2024-03-04 19:25 UTC, gino-m commented on functions/src/on-create-loi.ts
> +function removePrefixedKeys(obj: {[key: string]: string}, prefix: string) {
Also needs tsdoc

2024-03-06 20:11 UTC, gino-m approved these changes

2024-03-07 15:48 UTC, merged