Migrate to MDC based dialog component
google/ground-platform pull request #1567
Opened 2024-03-06 22:15 UTC by amysorto

There are a lot of files are touched here, but the MDC dialog does not differ much from the legacy. Some of this is unused code, but that should likely be a separate issue for code clean up.

2024-03-06 22:22 UTC, gino-m requested changes
Awesome! Can you paste a screen recording in the PR desc? Also note some checks are failing

2024-03-06 22:50 UTC, amysorto commented
> Awesome! Can you paste a screen recording in the PR desc? Also note some checks are failing

Would it make more sense to put all these PRs related to migrating to MDC into a branch, and then having a video walkthough of the entire app? Or do videos for each component?

2024-03-07 17:45 UTC, gino-m commented
> > Awesome! Can you paste a screen recording in the PR desc? Also note some checks are failing
> 
> Would it make more sense to put all these PRs related to migrating to MDC into a branch, and then having a video walkthough of the entire app? Or do videos for each component?

I think for velocity's sake we can skip the video now, since this is a cross-cutting change. Thanks!

2024-03-07 17:45 UTC, gino-m submitted a review, later dismissed

2024-03-12 12:28 UTC, rfontanarosa approved these changes

2024-03-12 12:28 UTC, merged