Fix import
google/ground-platform pull request #1590
Opened 2024-03-09 00:09 UTC by os-micmec

Towards #1576

2024-03-09 16:21 UTC, gino-m requested changes

2024-03-09 16:21 UTC, gino-m commented on functions/src/import-csv.ts
> +    console.error('unable to parse latitude and/or longitude values');
This error will not be visible to the user, I don't the we need to log it in the backend

2024-03-11 16:25 UTC, gino-m approved these changes
LGTM!

2024-03-12 13:22 UTC, rfontanarosa approved these changes

2024-03-12 13:22 UTC, merged