Read Submissions from Firestore using new proto-based format
google/ground-platform pull request #1918
Opened 2024-07-17 21:12 UTC by rfontanarosa

closes #1857

2024-07-18 10:48 UTC, gino-m requested changes
I realize this is still in draft, providing some early feedback.

2024-07-18 10:48 UTC, gino-m commented on web/src/app/converters/submission-data-converter.ts
> + * Copyright 2022 The Ground Authors.
2024 please

2024-07-18 10:48 UTC, gino-m commented on web/src/app/converters/submission-data-converter.ts
> +      if (typeof resultValue === 'number') {
Please chain with `else if` to make it clear there's no fall-through logic.

2024-07-19 14:14 UTC, gino-m requested changes
LG! Just a nit or two.

2024-07-19 14:14 UTC, gino-m commented on web/src/app/converters/submission-data-converter.ts
> +                  'otherOption',
Where do these special values `'otherOption'` come from? Can we refer to a const w/docs which explain their usage?

2024-07-25 06:56 UTC, sufyanAbbasi submitted a review, later dismissed
Thank you! I'll approve so we can merge this and iterate on this further!

2024-07-25 06:58 UTC, sufyanAbbasi commented
Note that this solution isn't fully complete because we still need to change all the places whenever we query the firestore, e.g. `where('jobId', ...`, those need to change to the field number instead. I'm happy to fix that after merging this one in!

2024-07-25 07:40 UTC, sufyanAbbasi commented
Ok, I went ahead and filled in the field numbers for all the queries!

2024-07-25 08:11 UTC, sufyanAbbasi approved these changes

2024-07-25 08:27 UTC, sufyanAbbasi commented
So part of the issue was that the app was not sending up the correct timestamp, it multiplied milliseconds by 1000. That is now fixed, but it still looks like TimeStamps are not being properly serialized just yet.

2024-07-25 08:55 UTC, sufyanAbbasi commented
I think the fix is something like in `toFieldValue()` in `firestore-to-proto.ts`, the deserializer should looks something like this but I can't seem to get it to work right now:
```ts
  switch (fieldType) {
    case 'string':
    case 'int32':
    case 'int64':
    case 'bool':
    case 'double':
      return firestoreValue;
    case '.google.protobuf.Timestamp':
      return toMessageOrEnumValue(['google', 'protobuf'], 'Timestamp', firestoreValue);
    default:
      return toMessageOrEnumValue(messageTypePath, fieldType, firestoreValue);
```

2024-07-25 18:36 UTC, sufyanAbbasi submitted a review, later dismissed
Thanks so much, approved! I'll take a look at the Timestamp proto serialization problem.

2024-07-25 23:03 UTC, sufyanAbbasi commented
It worked! Pushed a fix to this branch:

![image](https://github.com/user-attachments/assets/b397a801-c699-4033-b123-103eb211ebc1)

2024-07-25 23:23 UTC, sufyanAbbasi approved these changes
Ok now we should be good to go!!

2024-07-30 16:29 UTC, gino-m commented
@rfontanarosa Does this fix #1665? If so please add 'Fixes #1665' to the description.

2024-07-30 21:11 UTC, gino-m requested changes
Allmosttt theere! :D

2024-07-30 21:11 UTC, gino-m commented on web/src/app/services/data-store/data-store.service.ts
> +          [1, 2, 3]
Can we replace these with references to the enum values instead?

2024-07-30 21:11 UTC, gino-m commented on functions/src/common/datastore.ts
> +        // Field number for Submission.job_id.
You can remove this and similar comments now.

2024-07-30 21:11 UTC, gino-m commented on functions/src/on-write-submission.spec.ts
> +          .withArgs('2', '==', loiId)
Please use constant instead

2024-07-30 21:11 UTC, gino-m commented on web/src/app/services/data-store/data-store.service.ts
> +          [1, 2, 3]
Also, doesn't excluding the string values from the query immediately break backwards compatibility?

2024-07-30 21:22 UTC, gino-m requested changes
Also, something is breaking the build of `functions/`:

```
TypeError: Cannot read properties of undefined (reading 'v1beta1')
    at Object.<anonymous> (/home/runner/work/ground-platform/ground-platform/functions/src/import-geojson.ts:30:40)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:101[9](https://github.com/google/ground-platform/actions/runs/10169772702/job/28127451209?pr=1918#step:6:10):12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/runner/work/ground-platform/ground-platform/functions/src/import-geojson.spec.ts:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1422:[10](https://github.com/google/ground-platform/actions/runs/10169772702/job/28127451209?pr=1918#step:6:11))
npm error Lifecycle script `test` failed with error:
npm error Error: command failed
npm error   in workspace: @ground/functions@0.0.1
npm error   at location: /home/runner/work/ground-platform/ground-platform/functions
```

2024-07-31 14:19 UTC, gino-m requested changes

2024-07-31 14:19 UTC, gino-m commented on web/src/app/services/data-store/data-store.service.ts
> +          .where(FieldNumbers.LocationOfInterest.owner_id, '==', userId)
This and related changes will cause old submissions to stop showing once deployed. Is @lecrabe ok with us breaking existing surveys?

2024-07-31 14:19 UTC, gino-m commented on web/src/app/services/data-store/data-store.service.ts
> +        ref.where(FieldNumbers.LocationOfInterest.source, '==', Source.IMPORTED)
Consider also updating the name of variable from `predefined` and `user` to `imported` and `fieldData` for consistency.

2024-07-31 16:05 UTC, gino-m commented on web/src/app/services/data-store/data-store.service.ts
> +          .where(FieldNumbers.LocationOfInterest.owner_id, '==', userId)
We discussed. Let's merge but not deploy.

2024-07-31 16:05 UTC, gino-m approved these changes
Approved!

2024-07-31 16:08 UTC, merged