Use AdvancedMarkerElements and add index to markers on map
google/ground-platform pull request #2109
Opened 2024-11-27 15:45 UTC by amysorto

Part of #1477. Adds annotations for submission markers (but not polygons). @gino-m As far as I know we don't have polygons yet in our submissions. Should this PR close this issue instead and we file a separate issues for polygons?

I also filed #2108 to use custom HTML and CSS for the markers. When I initially tried the styles were not being correctly applied so I figured I can take a look into that separately so we can have better map annotiations in the meanwhile.
 
Screenshot:
<img width="1410" alt="Screenshot 2024-11-27 at 10 37 28 AM 1" src="https://github.com/user-attachments/assets/972532b5-5180-4203-a06d-58e66e93f646">

Also I changed the index in the submission panel to start at 1 instead of 0. I thought there was a filed issue for this but I couldn't find it to link it here.

2024-11-27 16:04 UTC, gino-m requested changes
Thanks, @amysorto! Lgtm, one small code health tax if you have time. 

@rfontanarosa for  final approval.

2024-11-27 16:04 UTC, gino-m commented on web/src/app/pages/main-page-container/main-page/map/map.component.ts
> +      ]).subscribe(
This method is becoming unwieldy. While you're here any chance you could refactor it a bit, perhaps pulling out meaningful logic into helper functions?

2024-12-10 19:47 UTC, gino-m commented
@amysorto Please ping when RFAL!

2024-12-10 20:25 UTC, amysorto commented
@gino-m This PR is ready for review!

2024-12-11 09:09 UTC, merged