Create pull_request_template.md
google/ground-platform pull request #502
Opened 2020-11-11 17:41 UTC by gino-m

..PTAL?

@shobhitagarwal1612 this template adds before and after screenshot; if you agree I can add this to https://github.com/google/ground-android/blob/master/.github/pull_request_template.md as well.

2020-11-11 18:02 UTC, shobhitagarwal1612 requested changes

2020-11-11 18:02 UTC, shobhitagarwal1612 commented on .github/ISSUE_TEMPLATE/pull_request_template.md
> +..
These should come after PR description and verification steps

2020-11-11 18:02 UTC, shobhitagarwal1612 commented on .github/ISSUE_TEMPLATE/pull_request_template.md
> +Closes #issueno
This will them move to the top

2020-11-11 18:03 UTC, shobhitagarwal1612 commented
> @shobhitagarwal1612 this template adds before and after screenshot; if you agree I can add this to https://github.com/google/ground-android/blob/master/.github/pull_request_template.md as well.

Yes, SGTM

2020-11-28 14:09 UTC, gino-m commented
@shobhitagarwal1612 RFAL!

2020-11-28 17:27 UTC, shobhitagarwal1612 approved these changes

2020-12-01 09:06 UTC, merged