Delete Observation Button added in overflow menu
google/ground-platform pull request #578
Opened 2020-12-27 06:25 UTC by gauravchalana1

Hey @gino-m Please review the PR for the Fix #70 and share your comments :) 

![image](https://user-images.githubusercontent.com/41099402/103165180-f5aa8300-47d9-11eb-8afd-db38812c8f3e.png)
![image](https://user-images.githubusercontent.com/41099402/103165182-f8a57380-47d9-11eb-85f3-e84f62f420ce.png)

2020-12-27 11:56 UTC, gino-m requested changes
👍 Great fix! A few minor suggestions, otherwise LGTM!

2020-12-27 11:56 UTC, gino-m commented on web-ng/src/app/components/feature-panel/feature-panel.component.html
> +          <span>Delete</span>
Let's use "Delete observation" for consistency and clarity.

2020-12-27 11:56 UTC, gino-m commented on web-ng/src/app/components/feature-panel/feature-panel.component.ts
> +  observationId?: string | null;
Can `| null` be removed from these two, letting `?` (undefined) cover the 'missing' case?

2020-12-27 11:56 UTC, gino-m commented on web-ng/src/app/components/feature-panel/feature-panel.component.ts
> +        this.projectId = id;
I think you can convert from `string | undefined | null` to `string | undefined` by replacing `id` with `id || undefined`.

2020-12-27 11:56 UTC, gino-m commented on web-ng/src/app/components/feature-panel/feature-panel.component.ts
> +        this.observationId = id;
Same here.

2020-12-28 02:25 UTC, gauravchalana1 commented
Hey @gino-m , please re-review the changes and share your comments :) tyty

2020-12-29 14:10 UTC, gino-m approved these changes
Nicely done! LGTM 🚀

2020-12-29 14:28 UTC, merged