[Project] Replace project URLs with more user friendly URLs
google/ground-platform pull request #600
Opened 2021-01-11 06:27 UTC by DakshSaini

Closes #590

2021-01-11 12:42 UTC, gino-m requested changes
Nice work! Would it be possible to roll a small refactor into this PR? Namely, it seems "project" and "new" are sprinkled across our codebase. As a quick fix, can we always refer to constants in the router instead? In a follow-up PR we can also replace calls to `this.router.navigate()` with methods in our `NavigationService`. Wdyt?

2021-01-12 09:54 UTC, DakshSaini commented
> Nice work! Would it be possible to roll a small refactor into this PR? Namely, it seems "project" and "new" are sprinkled across our codebase. As a quick fix, can we always refer to constants in the router instead? In a follow-up PR we can also replace calls to `this.router.navigate()` with methods in our `NavigationService`. Wdyt?

Sounds good, changes made. I'll be sure to create a follow-up PR.

2021-01-12 14:39 UTC, gino-m commented on web-ng/src/app/services/router/router.service.ts
> +  static readonly DEFAULT_PROJECT_ROUTE = 'project';
Why is this the "default" project route? Shouldn't it be something like the "project URL base path segment"? (`PROJECT_SEGMENT`?)

2021-01-12 14:39 UTC, gino-m commented on web-ng/src/app/services/router/router.service.ts
> +  static readonly SIGN_IN_ROUTE = 'signin';
Same here - this isn't a complete route, just a segment. Please rename accordingly.

2021-01-13 11:00 UTC, gino-m approved these changes
LGTM! Filed #605 for followup refactor. Thanks!!!

2021-01-13 11:00 UTC, merged