[Import CSV] Show upload progress and success/error message
google/ground-platform pull request #649
Opened 2021-04-29 01:54 UTC by parulraheja98

Relavant screenshots:

Error of CSV upload:

<img width="804" alt="Screen Shot 2021-04-28 at 8 42 42 PM" src="https://user-images.githubusercontent.com/27938664/116492603-4a323d80-a862-11eb-892a-fa0844ed475c.png">

Success of CSV upload:

<img width="802" alt="Screen Shot 2021-04-28 at 8 43 09 PM" src="https://user-images.githubusercontent.com/27938664/116492618-59b18680-a862-11eb-9e21-879cae23e797.png">

Loading state:

![spinner](https://user-images.githubusercontent.com/27938664/116493227-dd1fa780-a863-11eb-988a-a4bc9e1442e4.gif)

2021-05-10 08:09 UTC, jacobmclaws commented
Hey! @parulraheja98 Sure thing. Can I ask, when the CSV successfully uploads, what would the person see on the map? Usually some points would be added, correct? Layers/observations would probably appear in the side panel? Just asking so I know how much feedback we need to show the person when the upload is successful (if the screen noticeable changes then just a snackbar should work fine). 

Also, do we have any idea what some of the causes might be so that we could suggest any tips in the text when an upload fails?

2021-05-10 08:36 UTC, jacobmclaws commented
Here are my ideas so far. Let me know if this makes sense. 

**Loading state:** use the material [linear progress bar](https://kstatic.googleusercontent.com/files/b14128fc1118df8911bb9d5405a075c013d1f060e2fee2d6d78154f0d1143b41cbf1dc31d09de993bec3b18e078e8bcd4b226b245a394e70852d20d10a45f0e3)

Greens: primary 1EA362 ;  secondary 95CBB1
![image](https://user-images.githubusercontent.com/9397366/117629948-a4fa5c00-b1b5-11eb-975c-d228ccfce0cd.png)

**Successful upload:** use the material snackbar
![image](https://user-images.githubusercontent.com/9397366/117630233-f276c900-b1b5-11eb-809b-e22ba16967ca.png)

**Failed upload:** use the material banner with "Try again" and "Dismiss" buttons (I'd like to add more info about what might have gone wrong if we have any general tips we could add)
![image](https://user-images.githubusercontent.com/9397366/117630408-1df9b380-b1b6-11eb-9bfc-b4eaf88eb003.png)

2021-05-10 23:06 UTC, gino-m commented
> Hey! @parulraheja98 Sure thing. Can I ask, when the CSV successfully uploads, what would the person see on the map? Usually some points would be added, correct? Layers/observations would probably appear in the side panel? Just asking so I know how much feedback we need to show the person when the upload is successful (if the screen noticeable changes then just a snackbar should work fine).

Yes, that's correct. When upload succeed, new points should appear on the map. There's currently a delay between the upload completing and points appearing, we have a bug out to fix that (can't find it now).

> Also, do we have any idea what some of the causes might be so that we could suggest any tips in the text when an upload fails?

The most likely cause for the upload to fail would be the file being in the incorrect format. There are many things that can go wrong, and it may be useful to leave space for the exact error message returned from the server.

Thanks for the mocks, this is a big help! @parulraheja98, wdyt?

2021-05-12 18:14 UTC, gino-m commented
Hi @jacobmclaws, @parulraheja98 and I just spoke. A few questions/comments:

Regarding the progress line:

* Will the user be able to interact with the app while uploading? If so, what if they upload a second file while an upload is still in progress?
* If the upload hangs or simply takes too long, should there be a way for the user to cancel the upload?

Regarding the error banner:

* For security reasons, I'm fairly sure we can't cause the local file to be uploaded again, so "Try again" might now be possible.
* There's no Material banner component in Angular, so we'd have to create it ourselves. Since "Try again" action won't be there anyway, would a snackbar or similar be appropriate here?

Thanks again for your support!

2021-05-20 18:13 UTC, gino-m requested changes
A few small changes, PTAL!

2021-05-20 18:13 UTC, gino-m commented on web-ng/src/app/components/import-dialog/import-dialog.component.html
> +  <h2 mat-dialog-title>Import CSV</h2>
"CSV"->"features"

2021-05-20 18:13 UTC, gino-m commented on web-ng/src/app/components/import-dialog/import-dialog.component.html
> +<div *ngIf="isUploadingCSV; else defaultView">
`isUploadingCSV` -> `isImporting`

2021-05-20 18:13 UTC, gino-m commented on web-ng/src/app/components/import-dialog/import-dialog.component.ts
> +      this.notificationService.success('Csv import completed');
"Import complete" and "Importing features failed"

2021-05-21 06:35 UTC, parulraheja98 commented
RFAL! 
![Uploading image.png…]()

2021-05-21 16:05 UTC, gino-m approved these changes
💯 %! Thanks for the fix! This will provide a good base for more detailed progress indicators, and for my work on #696. 🥳

2021-05-21 16:05 UTC, merged

2021-05-21 16:06 UTC, gino-m commented on web-ng/src/styles.scss
> +  color: white;
@parulraheja98 Is there a `mat-color` we can use here instead? Perhaps submitted in a followup PR? :)