No observation text added
google/ground-platform pull request #652
Opened 2021-05-02 17:53 UTC by gauravchalana1

Hi @gino-m , PFB screenshot related to #477 ; Text added, please suggest for text customization. Thank you :) 

![Screen Shot 2021-05-02 at 12 43 53 PM](https://user-images.githubusercontent.com/41099402/116822607-4eea4080-ab45-11eb-89e9-53e3e166e011.png)

2021-05-03 19:57 UTC, gino-m requested changes
Thanks for this, very cool. One small suggestion, otherwise LGTM!

2021-05-03 19:57 UTC, gino-m commented on web-ng/src/app/components/feature-panel/feature-panel.component.scss
> +  color: #70757a;
Please use Angular themes to retrieve colors defined in https://github.com/google/ground-platform/blob/master/web-ng/src/app/shared/styles/_variables.scss. 

Examples:
https://github.com/google/ground-platform/search?q=mat-color

2021-05-12 22:32 UTC, gino-m commented
@gauravchalana1 Gentle ping!

2021-05-25 03:29 UTC, gauravchalana1 commented
Hi @gino-m , PFB screenshot and changes as suggested. Tyty :) 

![Screen Shot 2021-05-24 at 10 20 04 PM](https://user-images.githubusercontent.com/41099402/119434884-b7f54c00-bcde-11eb-9484-b6bbb412743d.png)

2021-05-25 04:01 UTC, gino-m submitted a review, later dismissed
🚀  Rockin'!! Thanks!

2021-05-25 04:01 UTC, gino-m commented
@gauravchalana1 Could you please resolve the merge conflicts when you get a chance?

2021-05-28 04:58 UTC, gauravchalana1 commented
Hi @gino-m , please re-review the PR. conflicts have been resolved. Tyty :)

2021-05-28 13:42 UTC, gino-m commented
Great work, thanks Gaurav!

2021-05-28 13:42 UTC, merged