created feature-list component
google/ground-platform pull request #780
Opened 2021-07-04 18:58 UTC by gauravchalana1

Hi @gino-m ,

On click layer, the URL will change to '#fl'. PFA screenshots.

<img width="301" alt="Screen Shot 2021-07-04 at 1 53 11 PM" src="https://user-images.githubusercontent.com/41099402/124396538-cb2d0b80-dccf-11eb-8123-e0f9331b68e0.png">
<img width="1439" alt="Screen Shot 2021-07-04 at 1 56 34 PM" src="https://user-images.githubusercontent.com/41099402/124396540-ce27fc00-dccf-11eb-9fe4-8abbe085a3ad.png">

Please review. Thank you!

2021-07-07 14:31 UTC, gino-m requested changes
A few suggestions. Thanks for the change.

2021-07-07 14:31 UTC, gino-m commented on web-ng/src/app/components/layer-list-item/layer-list-item.component.html
> +  <h3 matLine (click)="onLayerListSelect()">
Let's remove this until we have something to show in the list.

2021-07-07 14:31 UTC, gino-m commented on web-ng/src/app/components/feature-list/feature-list.component.html
> +<p>Feature List</p>
Please add copyright headers here and throughout.

2021-07-07 14:31 UTC, gino-m commented on web-ng/src/app/components/feature-list/feature-list.component.html
> +    * Todo: Display list of features for the layer!
Nit: add issue number like so:
```
<!--
  TODO(#...): ..
-->
```

2021-07-07 14:31 UTC, gino-m commented on web-ng/src/app/services/navigation/navigation.service.ts
> +  selectLayerFeature(id: string) {
Maybe `showFeatureList(layerId: string)` would be clearer?

2021-07-22 16:04 UTC, gino-m approved these changes
LGTM!! Welcome back! 👏

2021-07-22 16:06 UTC, gauravchalana1 commented
Thank you Sir 🙂

2021-07-22 16:09 UTC, merged